
# main search
search_bar:
  # search and generate
  keyword: ''
  # search engine(google, sogou)
  search_engine: 'google'

# folder paths
paths:
  # picture searched
  pic_searched_path: 'picture_searched'
  # picture generated
  pic_gen_path: 'picture_gen'

# configuration
settings:
  # number of picture to search
  search_num: 64
  # number of picture to generate
  gen_num: 3
  # image resolution (res_w x res_h)
  img_res_w: 256
  img_res_h: 256

  dcgan:
    num_workers: 4
    batch_size: 8
    epoch_num: 500
    latent_size: 100
    lr: 0.0002
    b1: 0.5
    b2: 0.999

  dragan:
    num_workers: 4
    batch_size: 8
    epoch_num: 120
    latent_size: 100
    lr: 0.0002
    b1: 0.5
    b2: 0.999